#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

if [ $# -eq 0 ]
then
  echo 'Usage: git-jira [issue number]' > /dev/stderr
  exit 2
fi

jira_host=$(git config git.jira.host) || true

if [ -z "$jira_host" ]
then
  echo "Error: Could not find a JIRA host set use 'git config git.jira.host <host>' to set one" > /dev/stderr
  exit 3
fi

jira_id=$1

jira_issue=$(curl --netrc --fail --silent --header 'Accept: application/json' \
  --url "https://$jira_host/rest/api/2/issue/$jira_id?fields=summary,issuetype")

issue_summary=$(echo "$jira_issue" | jq -r '.fields.summary' | sed -e "s/ /\\_/g" | tr "[:upper:]" "[:lower:]")

issue_type=$(echo "$jira_issue" | jq -r '.fields.issuetype.name' | sed -e "s/ /\\_/g" | tr "[:upper:]" "[:lower:]")

branch_name="$issue_type/$jira_id-$issue_summary"

if git rev-parse --quiet --verify "$branch_name" > /dev/null; then
  git checkout "$branch_name"
else
  git checkout -b "$branch_name"
fi
